# Database Configuration
database:
  host: localhost
  port: 5432
  user: admin
  password: admin
  name: loan_engine
  schema: public
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: 5m
  dsn: "postgres://admin:admin@localhost:5432/loan_engine"

jwt:
  secret: "your-super-secret-jwt-key-here"
