flowchart TD
    sysLoan((System Loan)) -- borrower --> proposeLoan[Propose Loan]

    subgraph State: Propose
        proposeLoan -- surveyor --> sb[Survey Borrower]
        sb --> inputDoc[Input Survey Document]
        inputDoc --> valDoc{Validation Document}
    end

    subgraph State: Approve
        valDoc -->|Invalid| loanReject[Loan Rejected]
        loanReject --> st(((Stop)))
        valDoc -->|Valid| approveLoan[Loan Approved]
        approveLoan --> generateTemplate[Generate Agreement Template]
    end

    subgraph State: Invest
        generateTemplate --> listingLoan[Listing Available Investment]
        listingLoan -- Investor --> makeInvestment[Make Investment]
        makeInvestment --> sendIndividualAgreement[Send Individual Agreement to Investor]
        sendIndividualAgreement --> updateTotal[Update Total Investment]
        updateTotal --> checkTotal{Total Investment = Principal?}

        checkTotal -->|No| listingLoan
        checkTotal -->|Yes| loanFullyInvested[Loan Fully Invested]
        loanFullyInvested --> sendCompletionNotification[Send Completion Notification to All Investors]
    end

    subgraph State: Disbursement
        sendCompletionNotification --> waitingDisbursement[Waiting for Disbursement]
        waitingDisbursement -- Field Officer --> collectSignedAgreement[Collect Signed Agreement from Borrower]
        collectSignedAgreement --> disbursement[Disburse to Borrower]
        disbursement --> loanActive[Loan Active]
    end

    loanActive --> e(((End)))
